src/assignments/urls.py
from django.urls import path 
from . import views

app_name = 'assignments'

urlpatterns = [
    path('<int:pk>/view-grades/', views.view_grades, name='view_grades'),
    path('<int:pk>/grade/', views.grade, name='grade'),
]

src/classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('posts/', include('posts.urls')),
    path('whiteboard/', include('whiteboard.urls')),
    path('assignments/', include('assignments.urls')),
    path('ide/', include('ide.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('contactus/', include('contactus.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ide/urls.py
from django.urls import path 
from . import views

app_name = 'ide'

urlpatterns = [
    path('', views.ide, name="ide"),
    path('problems/', views.problems, name="problems"),
]

src/classroom/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# members are not teachers
class Classroom(models.Model):
    name = models.CharField(max_length=200)
    classroom_code = models.CharField(max_length=20, blank=True)
    description = models.TextField(max_length=300)
    slug = models.SlugField(max_length=250,unique_for_date='created_at')
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(default=timezone.now)
    users = models.ManyToManyField(User,related_name='users')
    
    def __str__(self):
        return f'{self.name}'


# Memebers in this table are onl the teachers 
class ClassroomTeachers(models.Model):
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.teacher.username} -> {self.classroom.name}'


class Topic(models.Model):
    name = models.CharField(max_length=200)
    classroom = models.ForeignKey(Classroom,on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.classroom.name} -> {self.name}'
    

src/classroom/forms.py
from django.forms import ModelForm
from django import forms
from  .models import Classroom,Topic

class ClassroomCreationForm(ModelForm):
    class Meta:
        model = Classroom
        fields = ['name', 'description']

class JoinClassroomForm(forms.Form):
    code = forms.CharField(label='Enter Code', max_length=100)

class PostForm(forms.Form):
    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class AssignmentFileForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class AssignmentCreateForm(forms.Form):
    def __init__(self,user,*args, **kwargs):
        super(AssignmentCreateForm, self).__init__(*args,**kwargs)
        classrooms = list(map(lambda x: x.classroom, user.classroomteachers_set.all()))
        topics = []
        self.fields['classrooms'].choices = [(str(classroom.pk),classroom.name) for classroom in classrooms]
        for classroom in classrooms:
            topics.extend(list(classroom.topic_set.all()))
        self.fields['topics'].choices = [(str(topic.pk),f"{topic.name}->{topic.classroom.name}") for topic in topics]

    title = forms.CharField()
    description = forms.CharField(widget=forms.Textarea)
    classrooms = forms.ChoiceField()
    topics = forms.ChoiceField()
    points = forms.IntegerField(min_value=0,max_value =100)
    due_date = forms.DateTimeField()
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True})) 

src/classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required


from .models import Classroom,Topic,ClassroomTeachers
from posts.models import Assignment,SubmittedAssignment,AssignmentFile, Attachment
from .forms import ClassroomCreationForm,JoinClassroomForm, PostForm, AssignmentFileForm, AssignmentCreateForm
from comments.forms import CommentCreateForm, PrivateCommentForm

@login_required
def home(requests):
    teaching_classes = set([classroom.classroom for classroom in requests.user.classroomteachers_set.all()])
    classrooms = set(requests.user.classroom_set.all()).union(teaching_classes)
    classroom_form = ClassroomCreationForm()
    join_classroom_form = JoinClassroomForm()
    context = {
        'classrooms' : classrooms,
        'classroom_form': classroom_form,
        'join_classroom_form':join_classroom_form
    }
    return render(requests, 'classroom/home.html', context)

@login_required
def create_classroom(request):
    if request.method == 'POST':
        print('fORM vaLID')
        form = ClassroomCreationForm(request.POST)
        if form.is_valid(): 
            name = form.cleaned_data.get('name')
            description = form.cleaned_data.get('description')
            classroom = Classroom(name=name, description=description, created_by=request.user)
            classroom.save()
            classroom.classroom_code = classroom.name[:4] + str(classroom.id)
            classroom.save()
            topic = Topic(name = 'General' , classroom = classroom)
            topic.save()
            classroom_teachers = ClassroomTeachers(classroom = classroom, teacher=request.user)
            classroom_teachers.save()
            messages.success(request, f'Classroom {name} created !')
        else:
            messages.danger(request, f'Classroom Could not be created :(')
    return redirect('classroom:home')

@login_required
def join_classroom(request):
    if request.method == 'POST':
        print('fORM vaLID')
        form = JoinClassroomForm(request.POST)
        if form.is_valid(): 
            classroom = Classroom.objects.filter(classroom_code = form.cleaned_data.get('code')).first()
            if classroom:
                request.user.classroom_set.add(classroom)
                messages.success(request, f'You are added in {classroom.name}')
            else:
                messages.success(request, f'Error adding you to the classroom')
        else:
            messages.success(request, f'Error adding you to the classroom')
    return redirect('classroom:home')

@login_required
def open_classroom(requests,pk):
    classroom = get_object_or_404(Classroom,pk = pk)
    topics = classroom.topic_set.all()
    contents = []
    for topic in topics:
        contents.extend(list(topic.post_set.all()))
        contents.extend(list(topic.assignment_set.all()))
    
    contents.sort(key = lambda x: x.created_at)

    post_form = PostForm()
    comment_form = CommentCreateForm()

    context = {
        'classroom' : classroom,
        'contents': reversed(contents),
        'post_form': post_form,
        'comment_form': comment_form,
    }

    return render(requests, 'classroom/classroom.html', context)

@login_required
def delete_classroom(requests):
    context = {
        'title' : 'Classroom',
    }
    return render(requests, 'base.html', context)


@login_required
def members(request, pk):
    classroom = get_object_or_404(Classroom, pk=pk)
    context = {
        'teachers': classroom.classroomteachers_set.all(),
        'students': classroom.users.all(),
    }
    return render(request, 'classroom/members.html', context)

@login_required
def assignment_create(request):
    if request.method == 'POST':
        form = AssignmentCreateForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            topic = get_object_or_404(Topic, pk=int(form.cleaned_data['topics']))
            assignment = Assignment(
                title = form.cleaned_data['title'],
                description = form.cleaned_data['description'],
                created_by = request.user,
                topic = topic,
                due_date = form.cleaned_data['due_date']
            )
            assignment.save()
            files = request.FILES.getlist('file_field')
            for f in files:
                Attachment.objects.create(assignment = assignment,files=f)
            return redirect('classroom:open_classroom', topic.classroom.pk)

    else:
        form = AssignmentCreateForm(request.user)
    context = {'form':form}
    return render(request, 'classroom/assignment_create.html', context)


@login_required
def assignment_submit(request, pk):
    if request.method=='POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        if not submitted_assignment:
            submitted_assignment = SubmittedAssignment.objects.create(assignment = assignment, user = request.user)
        files = request.FILES.getlist('file_field')
        print(files)
        for f in files:
            AssignmentFile.objects.create(submitted_assignment = submitted_assignment,files=f)
    
    form = AssignmentFileForm()
    private_comment_form = PrivateCommentForm()
    assignment = get_object_or_404(Assignment, pk=pk)
    submit_assignment = assignment.submittedassignment_set.filter(user=request.user)
    classroom_teachers = list(map(lambda teaches: teaches.teacher, assignment.topic.classroom.classroomteachers_set.all()))
    print(classroom_teachers)
    is_teacher = request.user in classroom_teachers
    print(is_teacher)
    if submit_assignment:
        submit_assignment = submit_assignment.first()
        assignment_files = submit_assignment.assignmentfile_set.all()
    else: assignment_files = None


    context = {
        'assignment': assignment,
        'attachments': assignment.attachment_set.all(),
        'submitted_assignment': submit_assignment,
        'assignment_files': assignment_files,
        'form':form,
        'private_comment_form': private_comment_form,
        'is_teacher': is_teacher,
    }
    return render(request, 'classroom/assignment_submit.html', context)

@login_required
def turnin(request,pk):
    if request.method == 'POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        if not submitted_assignment:
            submitted_assignment = SubmittedAssignment.objects.create(assignment = assignment, user = request.user)
        submitted_assignment.turned_in = True 
        submitted_assignment.save()
        
    return redirect('classroom:assignment_submit', pk)

@login_required
def unsubmit(request,pk):
    if request.method == 'POST':
        assignment = get_object_or_404(Assignment,pk=pk)
        submitted_assignment = assignment.submittedassignment_set.filter(user = request.user).first()
        submitted_assignment.turned_in = False  
        submitted_assignment.save()
        
    return redirect('classroom:assignment_submit', pk)

@login_required
def unsubmit_file(request, pk):
    if request.method == 'POST':
        assignment_file = get_object_or_404(AssignmentFile, pk=pk)
        assignment_pk = assignment_file.submitted_assignment.assignment.pk
        if assignment_file.submitted_assignment.user == request.user:
            if assignment_file.submitted_assignment.turned_in:
                submitted_assignment = assignment_file.submitted_assignment
                submitted_assignment.turned_in = False  
                submitted_assignment.save()
            assignment_file.delete()
        return redirect('classroom:assignment_submit', assignment_pk)

@login_required
def todo(request):
    classrooms = request.user.classroom_set.all()
    topics = []
    for classroom in classrooms:
        topics.extend(list(classroom.topic_set.all()))
    assignments = []
    for topic in topics:
        assignments.extend(list(topic.assignment_set.all()))
    filtered_assignment = []
    for assignment in assignments:
        if not assignment.is_turnedin(request.user):
            filtered_assignment.append(assignment)
    context = {'assignments':filtered_assignment}
    
    return render(request, 'classroom/todo.html', context)




@login_required
def toreview(request):
    classrooms = request.user.classroomteachers_set.all()
    classrooms = list(map(lambda x: x.classroom, classrooms))
    topics = []
    for classroom in classrooms:
        topics.extend(classroom.topic_set.all())
    assignments = []
    for topic in topics:
        assignments.extend(topic.assignment_set.all())
    context = {'assignments': reversed(assignments)}
    return render(request, 'classroom/toreview.html', context)


@login_required
def classwork(request, pk):
    classroom = get_object_or_404(Classroom,pk=pk)
    assignments = []
    for topic in classroom.topic_set.all():
        assignments.extend(list(topic.assignment_set.all()))
    
    context = {'assignments':assignments}
    return render(request, 'classroom/classwork.html', context)

def student_work(request, pk):
    assignment = get_object_or_404(Assignment, pk=pk)
    context = {'assignment': assignment}
    return render(request, 'classroom/student_work.html', context)

src/classroom/templates/classroom/assignment_create.html
{% extends 'assignment_base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Assignment-Create {% endblock title %}

{% block content %}
<form action ="{% url 'classroom:assignment_create' %}" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    <nav class="navbar navbar-light bg-light">
        <div class="navbar-brand">
            <a href="{% url 'classroom:home' %}"><i class="fas fa-times"></i></a>
            <div class="pl-3 float-right">Assignment</div>
        </div>
        <div class="form-inline">
            <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                <button type="submit" class="btn btn-secondary">Assign</button>
                
<!--                <div class="btn-group" role="group">-->
<!--                    <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                    </button>-->
<!--&lt;!&ndash;                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">&ndash;&gt;-->
<!--&lt;!&ndash;                        <a class="dropdown-item" href="#">Dropdown link</a>&ndash;&gt;-->
<!--&lt;!&ndash;                        <a class="dropdown-item" href="#">Dropdown link</a>&ndash;&gt;-->
<!--&lt;!&ndash;                    </div>&ndash;&gt;-->
<!--                </div>-->
            </div>
        </div>
    </nav>
    <!-- Make a form here -->
    <div class="row m-3">
        <div class="col-lg-8">
            <div class="form-group">
                <label for="title">Title</label>
                {{ form.title|attr:"class:form-control" }}
            </div>
            <hr>
            <div class="form-group">
                <label for="description">Description</label>
                {{ form.description|attr:"class:form-control" }}
            </div>
            <hr>
            {{ form.file_field|attr:"class:choose" }}
        </div>
        <!-- <div class="col-1">
            <div class="vl d-sm-none d-md-block"></div>
        </div> -->
        <!-- The selection stuff -->
        <div class="col-lg-4 vl v p-3 mt-sm-2">
            <!-- For -->
            <hr class='d-lg-none d-sm-block'>
            <h5>For</h5>
            <div class="row">
                <div class="col">
                    {{ form.classrooms|attr:"class:form-control" }}
                </div>
                <!-- <div class="col">
                    <select id="" class="form-control" name="">
                        <option value="">Classroom1</option>
                        <option value="">Classroom2</option>
                        <option value="">Classroom3</option>
                    </select>
                </div> -->
            </div>
            <hr>
            
            <!-- Points -->
            <h5>Points</h5>
            <div class="row">
                <div class="col">
                    {{ form.points|attr:"class:form-control" }}
                </div>
            </div>
            <hr>

            <!-- Due -->
            <h5>Due</h5>
            <div class="row">
                <div class="col">
                    {{ form.due_date|attr:"class:form-control"|attr:"type:datetime-local" }}
                </div>
            </div>
            <hr>
            
            <!-- Topic -->
            <h5>Topic</h5>
            <div class="row">
                <div class="col">
                    {{ form.topics|attr:"class:form-control" }}
                </div>
            </div>
            <hr>

        </div>

    </div>
</form>
{% endblock content %}

src/classroom/templates/classroom/home.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %} Home {% endblock title %}

{% block content %}
<!-- Page Heading -->
<h1 class="h3 mb-4 text-gray-800">Classrooms</h1>
<!-- ROW  -->
<div class="row">
    <!-- COL -->
    {% for classroom in classrooms %}
    <div class="col-lg-3 col-md-4 col-sm-1">
        <!-- CARD -->
        <div class="card border-bottom-primary shadow mb-4">
            <div class="card-header py-3">
                <a href="{% url 'classroom:open_classroom' classroom.id %}">
                    <h6 class="m-0 font-weight-bold text-primary">{{ classroom.name }}</h6>
                </a>
            </div>
            <a href="#!">
                <div class="card-body">
                    <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="{% static 'mainapp/img/undraw_posting_photo.svg' %}" alt="">
                    </div>
                    <p class="text-secondary">{{ classroom.description }}</p>
                </div>
            </a>
        </div>
        <!-- END CARD -->
    </div>
    <!-- END COL -->
    {% endfor %}
</div>
<!-- END ROW -->

<!-- Modal Create Class -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create Class</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <form action="{% url 'classroom:create_classroom' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="exampleInput">Class Name</label>
                        {{ classroom_form.name|attr:'class: form-control'|attr:'placeholder:Enter Classname' }}
                    </div>
                    <div class="form-group">
                        <label for="exam">Description</label>
                        {{ classroom_form.description|attr:'class: form-control'|attr:'placeholder:Enter Description' }}
                    </div>
                </div>
            
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create Classroom</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal Join Class -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Join Class</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{% url 'classroom:join_classroom' %}" method="POST">
                {% csrf_token %}
                <div class="modal-body">
                        <div class="form-group">
                        <label for="exampleInput">{{ join_classroom_form.code.label }}</label>
                        {{ join_classroom_form.code|attr:'class: form-control'|attr:'placeholder:Enter Class Code' }}
                        <small id="Help" class="form-text text-muted">Ask your teacher for the class code, then enter it here.</small>
                        </div>
                    <ul><h5>To sign in with a class code</h5>
                        <li>Use an authorized account</li>
                        <li>Use a class code with 5-7 letters or numbers, and no spaces or symbols</li>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Join Classroom</button>
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

src/classroom/templates/classroom/members.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Home {% endblock title %}


{% block content %}
<div class="col-lg-8 mx-auto">
    <!-- Teachers -->
    <h3 class="text-primary font-weight-bold">Teachers</h3>
    <hr>

    {% for teacher in teachers %}
      <div class="row">
        <img width="25px" height="25px" class="img-profile rounded-circle" src="{{ teacher.teacher.profile.image.url }}">
        <p class="text-dark">{{ teacher.teacher.username }}</p>
        <button class="ml-auto btn btn-secondary">mail</button>
      </div>
      <hr>
    {% endfor %}




    <!-- Students -->
    <div class="row mt-4">
      <div class="col-lg-8">
        <h3 class="text-primary font-weight-bold">Students</h3>
      </div>
      <div class="col-lg-4 ">
        <p class="text-primary ml-auto float-right">{{ students|length }}</p>
      </div>
    </div>
    <hr>

    {% for student in students %}
      <div class="row">
        <img width="25px" height="25px" class="img-profile rounded-circle" src="{{ student.profile.image.url }}">
        <p class="text-dark">{{ user.username }}</p>
        <button class="ml-auto btn btn-secondary">mail</button>
      </div>
      <hr>
    {% endfor %}

{% endblock content %}

src/classroom/templates/classroom/student_work.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} Home {% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <h3>{{ assignment.title }}</h3>
        </div>
        <div class="col-lg-12">
        <ul class="navbar-nav">
            <div class="row">
                <li class="nav-item ml-2">
                    <h1>{{ assignment.total_turned_in }}</h1>
                    <small class='text-success'>Turned in</small>
                </li>
                <li class="nav-item ml-4">
                    <h1>{{ assignment.total_missing }}</h1>
                    <small class='text-danger'>Missing</small>
                </li>
            </div>
        </ul>
        </div>
    </div>

    <!-- Cards -->
    <div class="row">
        <div class="dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Assigned
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">All</a>
                <a class="dropdown-item" href="#">Turned in</a>
                <a class="dropdown-item" href="#">Graded</a>
            </div>
        </div>
    </div>



    <!-- Cards -->

    <div class="row">
        {% for ass in assignment.submitted_assignments %}
            <div class="col-lg-3 m-2 ">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-row">
<!--                            <img src="{{ ass.user.profile.image.url }}" width="35" height="35" alt="..." class="rounded-circle mr-2 mb-2 float-left">-->
                            <p class="pt-2">{{ ass.user.username }}</p>
                            
                            <a class="btn btn-circle ml-auto" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-ellipsis-v fa-sm fa-fw text-dark"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'assignments:grade' assignment.pk %}">Grade Student</a>
                            </div>
                        </div>
                        
                        {% if ass.file_count >= 1 %}
                            <img class = "img-fluid" src="{{ ass.first_file_url }}" alt="" srcset="">
                        {% endif %}
                        <div class="mt-1">
                            <a href="#" class="card-link">{{ ass.file_count }}</a>
                            {% if ass.turned_in %}
                                <a href="#" class="card-link text-success">Turned In</a>
                            {% else %}
                                <a href="#" class="card-link text-danger">Missing</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

src/classroom/templates/classroom/toreview.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %} To Review {% endblock title %}

{% block content %}
<!-- <div class="ml-lg-5 mr-lg-5">
    <div class="d-flex flex-row bd-highlight mb-3">
        <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</button>
        <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
        <div role="separator" class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
        </div>
    </div>
</div> -->
<div class = "ml-lg-5 mr-lg-5">
    <div class="accordion" id="accordionExample">
      {% for assignment in assignments %}
        <!-- CARD -->
        <div class="card mb-2">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapse{{ assignment.pk }}" aria-expanded="true" aria-controls="collapseOne">
                {{ assignment.title }}
              </button>
            </h2>
          </div>
          <div id="collapse{{ assignment.pk }}" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
               <small>Posted on {{ assignment.created_at }}</small>
               <p>{{ assignment.description }}</p>
               <div class = "d-flex flex-row-reverse">
                    <div class="p-2 border-left border-secondary">
                        <h1 class="text-dark">{{ assignment.total_turned_in  }}</h1>
                        <br>
                        <p>Turned in</p>
                    </div>
                    <div class="p-2 border-left border-secondary">
                        <h1 class="text-dark">{{ assignment.total_missing }}</h1>
                        <br>
                        <p>Missing</p>
                    </div>
               </div>
            <hr>
            <div class="d-flex flex-row bd-highlight mb-3">
                <a class = "p-2" href = "{% url 'classroom:assignment_submit' assignment.pk %}" >View Assignment</a>
                <a class = "p-2" href = "{% url 'classroom:student_work' assignment.pk %}" >View Submissions</a>
                <a class = "p-2" href = "{% url 'assignments:view_grades' assignment.pk %}" >View Grades</a>
            </div>
          </div>
        </div>
      </div>
      <!-- END CARD -->
      {% endfor %}
</div>


{% endblock %}