src/classroom/urls.py
from django.urls import path 
from . import views

app_name = 'classroom'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_classroom, name = 'create_classroom'),
    path('join/', views.join_classroom, name = 'join_classroom'),
    path('open/<int:pk>/', views.open_classroom, name = 'open_classroom'),
    path('<int:pk>', views.delete_classroom, name = 'delete_classroom'),
    path('<int:pk>/members', views.members, name = 'members_classroom'),
    path('assignment/<int:pk>/student_work', views.student_work, name = 'student_work'),
    path('assignment/create', views.assignment_create, name = 'assignment_create'),
    path('assignment/<int:pk>', views.assignment_submit, name = 'assignment_submit'),
    path('assignment/<int:pk>/turnin/', views.turnin, name = 'turnin'),
    path('assignment/<int:pk>/unsubmit/', views.unsubmit, name = 'unsubmit'),
    path('assignment/<int:pk>/unsubmit_file/', views.unsubmit_file, name = 'unsubmit_file'),
    path('todo/', views.todo, name = 'todo'),
    path('toreview/', views.toreview, name = 'toreview'),
    path('<int:pk>/classwork/', views.classwork, name = 'classwork'),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views


from . import views


urlpatterns = [
    path('comments', include('comments.urls')),
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls')),
    path('', views.landing, name='landing-page'),
    path('users/', include('users.urls')),
    path('courses/', include('courses.urls')),
    path('posts/', include('posts.urls')),
    path('whiteboard/', include('whiteboard.urls')),
    path('assignments/', include('assignments.urls')),
    path('ide/', include('ide.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('contactus/', include('contactus.urls')),
    path('password-reset/', 
    auth_views.PasswordResetView.as_view(
        template_name = 'users/password_reset.html'),
        name = 'password_reset'
    ),
    path('password-reset/done/', 
    auth_views.PasswordResetDoneView.as_view(
        template_name = 'users/password_reset_done.html'),
        name = 'password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
    ),
        name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
    ),
      name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/courses/urls.py
from django.urls import path 
from . import views

app_name = 'courses'

urlpatterns = [
    path('course-list', views.course_list, name='course_list'),
    path('create-course', views.create_course, name='create_course'),
    path('update-course/<int:pk>', views.update_course, name='update_course'),
    path('delete-course/<int:pk>', views.delete_course, name='delete_course'),
]

src/ide/urls.py
from django.urls import path 
from . import views

app_name = 'ide'

urlpatterns = [
    path('', views.ide, name="ide"),
    path('problems/', views.problems, name="problems"),
]

src/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings

from . import views

app_name= 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name="users/login.html"),name="login"),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},name="logout"),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
]

src/whiteboard/urls.py
from django.urls import path 
from . import views

app_name = 'whiteboard'

urlpatterns = [
    path('', views.whiteboard, name='whiteboard'),
    path('live/', views.live, name='live'),
]

src/core/views.py
from django.shortcuts import render
from newsletter.forms import SubscribeForm
from contactus.forms import ContactUsForm

def landing(request):
    subscribe_form = SubscribeForm()
    contactus_form = ContactUsForm()
    context = {
        'title': "Home",
        'subscribe_form':subscribe_form,
        'contactus_form':contactus_form
        }
    return render(request, "landing_page.html", context)

src/core/templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error: 
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

src/core/templates/partials/_footer.html
<!-- Footer -->
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

src/core/templates/partials/_head.html
{% load static %}


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  
    
  
    <!-- Custom fonts for this template-->
    <link href="{% static 'mainapp/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  
    <!-- Custom styles for this template-->
    <link href="{% static 'mainapp/css/sb-admin-2.min.css' %}" rel="stylesheet">
    
    <!-- Custom Styles -->
    <link rel="stylesheet" href="{% static 'mainapp/css/styles.css' %}">


     <!-- Bootstrap core JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery/jquery.min.js' %}" defer></script>
    <script src="{% static 'mainapp/vendor/bootstrap/js/bootstrap.bundle.min.js' %}" defer></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'mainapp/vendor/jquery-easing/jquery.easing.min.js' %}" defer></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'mainapp/js/sb-admin-2.min.js' %}" defer></script>

    <script src="{% static 'mainapp/js/script.js' %}" defer></script>

    {% if 'todo' in request.path %}
        <script src="{% static 'mainapp/js/todo.js' %}" defer></script>
    {% endif %}

src/core/templates/partials/_logout_modal.html
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'users:logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

src/core/templates/partials/_sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'classroom:home' %}">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-book-open"></i>
      </div>
      <div class="sidebar-brand-text mx-3"> VJTI CLASSROOM </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:home' %}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Classrooms</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Options
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'classroom:home' %}">
        <i class="fas fa-fw fa-cog"></i>
        <span>Classrooms</span>
      </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:todo' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Do</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:toreview' %}" >
        <i class="fas fa-fw fa-wrench"></i>
        <span>To Review</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'classroom:assignment_create' %}">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Create Assignment</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Features
    </div>

    <!-- Nav Item - Pages Collapse Menu -->

    {% if 'open' in request.path %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'classroom:classwork' classroom.pk %}" >
          <i class="fas fa-fw fa-folder"></i>
          <span>Classworks</span>
        </a>
      </li>
    {% endif %}

    <!-- Nav Item - Charts -->
    



    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'whiteboard:whiteboard' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Whiteboard</span></a>
    </li>
    <!-- Nav Item - Tables -->
<!--    <li class="nav-item">-->
<!--      <a class="nav-link" href="{% url 'whiteboard:live' %}">-->
<!--        <i class="fas fa-fw fa-table"></i>-->
<!--        <span>Liveboard</span></a>-->
<!--    </li>-->

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'courses:course_list' %}">
        <i class="fas fa-fw fa-table"></i>
        <span>Courses</span></a>
    </li>

    <!-- Nav Item - Tables -->
<!--    <li class="nav-item">-->
<!--      <a class="nav-link" href="{% url 'ide:ide' %}">-->
<!--        <i class="fas fa-fw fa-table"></i>-->
<!--        <span>IDE</span></a>-->
<!--    </li>-->

     <!-- Nav Item - Tables -->
<!--     <li class="nav-item">-->
<!--      <a class="nav-link" href="{% url 'ide:problems' %}">-->
<!--        <i class="fas fa-fw fa-table"></i>-->
<!--        <span>Problem Statements</span></a>-->
<!--    </li>-->

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->